apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: optiinfra-staging

bases:
  - ../../base

namePrefix: staging-

commonLabels:
  environment: staging

replicas:
  - name: portal
    count: 1

images:
  - name: optiinfra/cost-agent
    newName: ghcr.io/optiinfra/optiinfra/cost-agent
    newTag: develop
  - name: optiinfra/performance-agent
    newName: ghcr.io/optiinfra/optiinfra/performance-agent
    newTag: develop
  - name: optiinfra/resource-agent
    newName: ghcr.io/optiinfra/optiinfra/resource-agent
    newTag: develop
  - name: optiinfra/application-agent
    newName: ghcr.io/optiinfra/optiinfra/application-agent
    newTag: develop
  - name: optiinfra/portal
    newName: ghcr.io/optiinfra/optiinfra/portal
    newTag: develop

configMapGenerator:
  - name: environment-config
    literals:
      - ENVIRONMENT=staging
      - LOG_LEVEL=DEBUG
